name: Spring Boot CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give permission to mvnw
        run: chmod +x mvnw

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      - name: Upload JAR file
        uses: actions/upload-artifact@v4   # ✅ FIXED
        with:
          name: spring-boot-app
          path: target/*.jar
